# Generated by Django 2.2.28 on 2022-11-04 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0009_auto_20221104_1532'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_custom_generic_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlegroupobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AddField(
            model_name='articleuserobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AddField(
            model_name='biggroupobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AddField(
            model_name='biguserobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AlterUniqueTogether(
            name='articlegroupobjectpermission',
            unique_together={('group', 'permission', 'content_object', 'origin')},
        ),
        migrations.AlterUniqueTogether(
            name='articleuserobjectpermission',
            unique_together={('user', 'permission', 'content_object', 'origin')},
        ),
        migrations.AlterUniqueTogether(
            name='biggroupobjectpermission',
            unique_together={('group', 'permission', 'object_pk', 'origin')},
        ),
        migrations.AlterUniqueTogether(
            name='biguserobjectpermission',
            unique_together={('user', 'permission', 'object_pk', 'origin')},
        ),
    ]
