# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0006_auto_20170124_0803'),
        ('testapp', '0008_auto_20161207_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixedgroupobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AddField(
            model_name='projectgroupobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AddField(
            model_name='projectuserobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AddField(
            model_name='reversemixeduserobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AlterUniqueTogether(
            name='mixedgroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object', 'origin')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object', 'origin')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectuserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object', 'origin')]),
        ),
        migrations.AlterUniqueTogether(
            name='reversemixeduserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object', 'origin')]),
        ),
    ]
