# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_auto_20161207_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobjectpermission',
            name='user_group_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.UserGroupObject'),
        ),
        migrations.AlterUniqueTogether(
            name='userobjectpermission',
            unique_together=set([('user', 'permission', 'object_pk', 'user_group_object')]),
        ),
    ]
