# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-07 16:18
from __future__ import unicode_literals

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_auto_20161207_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AlterUniqueTogether(
            name='userobjectpermission',
            unique_together=set([('user', 'permission', 'object_pk', 'origin')]),
        ),
    ]
