# Generated by Django 3.2.16 on 2022-11-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_generic_permissions_index'),
        ('guardian', '0007_auto_20170628_1735'),
    ]

    operations = [
    ]
