# Generated by Django 2.2.28 on 2022-11-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0008_merge_20221104_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardian.Origin'),
        ),
    ]
